server:
  port: 8085
spring:
  datasource:                               # mysql数据库 主业务库
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/its?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: Root@123
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 99               # 最大连接数
        minimum-idle: 30                    # 最小空闲连接
        connection-test-query: SELECT 1     # 连接测试查询
        connection-timeout: 60000           # 连接超时时间 毫秒
    secondary:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;Databasename=NIC_DB
      username: SA
      password: Root@123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true                  # 格式化SQL
        use_sql_comments: true            # 生成JPQL语句
        generate_statistics: false        # 显示SQL性能分析日志
sms:
  application-id: A000000000000054
  application-password: HITjt_#2021@hit!
  send-sms-url: http://uc.hit.edu.cn:8099/HitGateWay/SendSms
weLink:
  ##获取access token的请求地址
  ticket:
    url: https://open.welink.huaweicloud.com/api/auth/v2/tickets
  ##获取免登用户userId的请求地址
  user:
    url: https://open.welink.huaweicloud.com/api/auth/v2/userid
  ##对应We码开发平台H5应用的appid
#  client为本地参数，服务器中的配置文件为生产参数
  client:
    id: 20211026155556354661433
  ##对应We码开发平台H5应用的appsecret
    secret: 72a3fdea-765d-4cf0-bfec-b276999d14e0