server:
  port: 8084
  servlet:
    session:
      cookie:
        name: its_session_id
spring:
  datasource:                               # mysql数据库 主业务库
    primary:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/its?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: Root@123
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 99               # 最大连接数
        minimum-idle: 30                    # 最小空闲连接
        connection-test-query: SELECT 1     # 连接测试查询
        connection-timeout: 60000           # 连接超时时间 毫秒
    secondary:
      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;Databasename=NIC_DB
      username: SA
      password: Root@123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true                  # 格式化SQL
        use_sql_comments: false            # 生成JPQL语句
        generate_statistics: false         # 显示SQL性能分析日志
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: its
    password: its@123456
    virtual-host: /its
    connection-timeout: 1000ms
fdfs:
  connect-timeout: 10000                  # 毫秒
  tracker-list:                           # TrackerList参数,支持多个
    - 192.168.3.112:22122
  pool:
    max-total: 100                        # 从池中借出的对象的最大数目
    max-total-per-key: 50                 # 每个tracker地址的最大连接数
    max-wait-millis: 5000                 # 连接耗尽时等待获取连接的最大毫秒数
sms:
  enable: false
  template: 您的车辆{0}于{1}在{2}，被交通技术监控设备记录了{3}的违法行为。给予{4}处罚，请知悉。详情请登录哈工大APP进行查询。
  black-template: 您的车辆{0} 校内违规次数已达上限，车辆入校权限已被取消，时限为一个月，请知悉。详情请登录哈工大APP进行查询。
  application-id: A000000000000054
  application-password: HITjt_#2021@hit!
  send-sms-url: http://uc.hit.edu.cn:8099/HitGateWay/SendSms
  welink-url: http://127.0.0.1:8085/message
management:
  endpoints:
    web:
      exposure:
#        include: '*'
        exclude: '*'
  endpoint:
    health:
      show-details: never
logging:
  level:
    web: off
    org.hibernate.type.descriptor.sql.BasicBinder: trace