server:
  port: 8084
  servlet:
    session:
      cookie:
        name: its_session_id
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/its?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 99               # 最大连接数
      minimum-idle: 30                    # 最小空闲连接
      connection-test-query: SELECT 1     # 连接测试查询
      connection-timeout: 60000           # 连接超时时间 毫秒
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true                  # 格式化SQL
        use_sql_comments: true            # 生成JPQL语句
        generate_statistics: false        # 显示SQL性能分析日志
  rabbitmq:
    host: 121.5.59.101
    port: 5672
    username: its
    password: its@123456
    virtual-host: /its
sms:
  application-id: 11111
  application-password: 222222
  send-sms-url: http://uc.hit.edu.cn:8099/HitGateWay/SendSms
